### PR TITLE
Added ability to bind to a specific IP interface

### PR DESCRIPTION
**Pull request by sijanec**
~~Not tested yet though~~ Tested and works

### CODE REVIEW

**Comment by qubard** [comment]
The only problem with this is that if the default is `'127.0.0.1'` that's specifically LAN or localhost which means you can't connect to it from outside LAN. If you change the default to `''` (the empty string) it has the desired behaviour though.

**Comment by sijanec** [comment]
Isn't localhost already the default behavior?

V V čet., 21. maj 2020 ob 22:31 je oseba cub
<notifications@github.com> napisala:

**Comment by qubard** [comment]
Just merged your changes. And according to the [docs ](https://docs.python.org/3/library/socket.html)

"For IPv4 addresses, two special forms are accepted instead of a host address: '' represents INADDR_ANY, which is used to bind to all interfaces, and the string '<broadcast>' represents INADDR_BROADCAST. This behavior is not compatible with IPv6, therefore, you may want to avoid these if you intend to support IPv6 with your Python programs."

So it works as both `localhost` and any external address

**Comment by sijanec** [comment]
Oh, you're right. I haven't RTFD (:

**Pull request merged**
